### ISSUE TITLE
Failing on Rasbperry + Libreelec

### ISSUE THREAD

**Issue by robertvanya** [AnonTester/context.youtube.dl.menu#1]
Hello, I've just intalled the newest Libreelec 10.0.2 with Kodi 19.1 on a RPi 3. The add-on is not working.
First, it throws an error in /lib/ytcontext.py, lin 581, due to using an unitialized variable addon_created_new_dir. It's really not initialized.
Second, it fails the test on line 560, saying in a popup that the source file does not exist. Really, the file in the temp folder has an extension .mp4, but the variable "filename" does not contain it. Line 544 is bulding the filename, but uses a variable finalformat what is always empty - set by line 518. When I put there 'mp4' (just for testing), works well. Is it a bug?
What I don't understand, that the plugin works well on my Ubuntu desktop PC. Please try to fixt the issue. Thank you!

**Comment by AnonTester** [comment]
true, addon_created_new_dir isn't initialised and needs to be fixed. It erroneously assumes there's always a target dir created that needs to be cleaned up.

finalformat is being set while downloading and monitoring the output from youtube-dl and should be set to mkv/webm/mp4 through the MyLogger class which is being used in lines 412+419 showing the download progress. If you fix this to mp4, this will work as long as the resulting downloaded files are always mp4, but this will fail if incompatible audio/video streams are merged and youtube-dl will create an mkv or if the video is webp.
Not sure why this doesn't work on your RPI. Could you please send me a link to a debug log (paste.kodi.tv or pastebin, it might shed some light on where this is going wrong.

**Comment by robertvanya** [comment]
The log file:
https://paste.kodi.tv/ovajefowep.kodi

Line 37 shows there's .mp4 at the end of the file name. But line 41 is looking for a file name without the mp4 at the end, and this fails.

**Comment by AnonTester** [comment]
This should fix both issues. Please test and let me know. I think this is because in all my tests ffmpeg merged files and therefore, the original filename and extension was never the final extension. This fix should set the initial extension and amend it if it's different. *fingers crossed*

**Comment by robertvanya** [comment]
Unfortunatelly, still throws the same "source file missing" error. I've checked, and now the fileformat is good. I attach a new log. Line 34 was added by me, to see what is in the filename variable. There the filename is OK, and contains .mp4 at the end. The real filename int the temp folder is matching. But, when later building the file path, it becomes somehow wierd, there are 3 points before the mp4 extension instead of 1 point. See log line 40, where are already 2 points, and finally line 45, where are already 3 points, and there it fails. Somehow the points are multiplying.
Log: https://paste.kodi.tv/mivumeraxe.kodi

**Comment by robertvanya** [comment]
I did one more test, and found, that variable finalformat on line 568 contains ".mp4", instead of "mp4". Can't this cause the growing appearance of the points in the name?

**Comment by AnonTester** [comment]
Yeah, finalformat shouldn't contain the dot of the extension as that's added separately.
Could you test by adjusting line 568 to:
`finalformat = os.path.splitext(filename)[1][1:]`

**Comment by robertvanya** [comment]
Works well now! Might worth to add also some edge case checks, to not damage the functionality on places where it currently works (for example on my Ubunut PC it works even without these mods).
Thank you for the quick resolution!

**Comment by AnonTester** [comment]
Based on the logs, you don't appear to have ffmpeg or avconv on your pi. In that case the youtube-dl options are set to use the best single stream based on the max resolution (lines 466-471) and not pick the best video stream and best audio stream and combine them if necessary. That's why the existing filename extension code failed as there won't be any merging on your pi. On your ubuntu system you will have ffmpeg installed and the coding worked. I accounted for, but didn't test that.

Committed now. Thanks for raising this error.
